## YAML Template.
services:
    app.repositories.note:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
          - AppBundle:Note